package main

import (
	"fmt"
	"net"
	"os"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/kawaiipantsu/synapseids/internal/capture/pcapoverip"
)

// ---------------------------------------------------------------- conf parser

func TestParseSensorConf(t *testing.T) {
	const rendered = `# Generated by OPNsense - do not edit.
synapseids_sensor_enable="YES"
synapseids_sensor_iface="em0"
synapseids_sensor_iface_id="wan"
synapseids_sensor_iface_src="interfaces.wan.if"
synapseids_sensor_iface_error=""
synapseids_sensor_args="--listen 0.0.0.0:4789 --iface em0 --filter ip-any --direction in --promisc --snaplen 262144 --sensor-id 'opnsense wan' --location 'dmz/edge' --authorized"
`
	conf, err := parseSensorConf(strings.NewReader(rendered))
	if err != nil {
		t.Fatalf("parseSensorConf: %v", err)
	}
	if !conf.enabled() {
		t.Errorf("enabled() = false, want true")
	}
	if got := conf.get("synapseids_sensor_iface"); got != "em0" {
		t.Errorf("iface = %q, want em0", got)
	}
	if got := conf.get("synapseids_sensor_iface_src"); got != "interfaces.wan.if" {
		t.Errorf("iface_src = %q", got)
	}
	if got := conf.transport(); got != "listen" {
		t.Errorf("transport = %q, want listen", got)
	}
	args := conf.args()
	for flag, want := range map[string]string{
		"--listen":    "0.0.0.0:4789",
		"--iface":     "em0",
		"--filter":    "ip-any",
		"--direction": "in",
		"--snaplen":   "262144",
		"--sensor-id": "opnsense wan",
		"--location":  "dmz/edge",
	} {
		if got := flagValue(args, flag); got != want {
			t.Errorf("flagValue(%s) = %q, want %q", flag, got, want)
		}
	}
	for _, flag := range []string{"--promisc", "--authorized"} {
		if !hasFlag(args, flag) {
			t.Errorf("hasFlag(%s) = false, want true", flag)
		}
	}
	if hasFlag(args, "--insecure-tls") {
		t.Error("hasFlag(--insecure-tls) = true, want false")
	}
	// A quoted value containing a space must not be split into two words, or the
	// sensor-id would be truncated in the daemon's capture-sources view.
	if got := len(args); got != 16 {
		t.Errorf("args length = %d (%q), want 16", got, args)
	}
}

// The rc.d script sources sensor.conf as root, so anything the shell would
// re-interpret must be rejected rather than silently accepted.
func TestParseSensorConfRejectsShellInjection(t *testing.T) {
	for name, body := range map[string]string{
		"command substitution": "a=\"x\"\nsynapseids_sensor_args=\"--iface $(id)\"\n",
		"backtick":             "a=\"x\"\nsynapseids_sensor_args=\"--iface `id`\"\n",
		"variable expansion":   "a=\"x\"\nsynapseids_sensor_args=\"--iface ${HOME}\"\n",
		"semicolon":            "a=\"x\"\nsynapseids_sensor_args=\"--iface em0; rm -rf /\"\n",
		"pipe":                 "a=\"x\"\nsynapseids_sensor_args=\"--iface em0 | sh\"\n",
		"not name=value":       "this is not a shell fragment\n",
		"bad variable name":    "9bad=\"x\"\n",
		"empty":                "# only a comment\n",
	} {
		t.Run(name, func(t *testing.T) {
			if _, err := parseSensorConf(strings.NewReader(body)); err == nil {
				t.Fatalf("parseSensorConf(%q) succeeded, want an error", body)
			}
		})
	}
}

func TestSplitShellWords(t *testing.T) {
	for _, tc := range []struct {
		in   string
		want []string
	}{
		{"", nil},
		{"   ", nil},
		{"--a b", []string{"--a", "b"}},
		{"--a  'b c'  --d", []string{"--a", "b c", "--d"}},
		{`--a "b c"`, []string{"--a", "b c"}},
		{"--a ''", []string{"--a", ""}},
		{"\t--a\tb\t", []string{"--a", "b"}},
	} {
		got := splitShellWords(tc.in)
		if fmt.Sprint(got) != fmt.Sprint(tc.want) {
			t.Errorf("splitShellWords(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestFlagValueEqualsForm(t *testing.T) {
	args := []string{"--connect=ids.example:4789", "--iface", "em0", "--cert"}
	if got := flagValue(args, "--connect"); got != "ids.example:4789" {
		t.Errorf("--connect = %q", got)
	}
	if got := flagValue(args, "--iface"); got != "em0" {
		t.Errorf("--iface = %q", got)
	}
	// A trailing flag with no value must not consume the next flag.
	if got := flagValue(args, "--cert"); got != "" {
		t.Errorf("--cert = %q, want empty", got)
	}
	if got := flagValue(args, "--nope"); got != "" {
		t.Errorf("--nope = %q, want empty", got)
	}
}

// ---------------------------------------------------------------- fixtures

// doctorFixture builds a temporary tree that looks like a correctly deployed
// sensor, and returns the env pointing at it.
type doctorFixture struct {
	env      doctorEnv
	etcDir   string
	logDir   string
	iface    string
	certPath string
	keyPath  string
	caPath   string
}

func newDoctorFixture(t *testing.T) *doctorFixture {
	t.Helper()
	root := t.TempDir()
	etcDir := filepath.Join(root, "etc")
	logDir := filepath.Join(root, "log")
	for _, d := range []string{etcDir, logDir} {
		if err := os.MkdirAll(d, 0o750); err != nil {
			t.Fatal(err)
		}
	}

	_, certPEM, keyPEM, err := pcapoverip.SelfSignedCert("127.0.0.1")
	if err != nil {
		t.Fatal(err)
	}
	f := &doctorFixture{
		etcDir:   etcDir,
		logDir:   logDir,
		iface:    firstLocalInterface(t),
		certPath: filepath.Join(etcDir, "sensor-cert.pem"),
		keyPath:  filepath.Join(etcDir, "sensor-key.pem"),
		caPath:   filepath.Join(etcDir, "sensor-ca.pem"),
	}
	write(t, f.certPath, certPEM, 0o444)
	write(t, f.caPath, certPEM, 0o444)
	write(t, f.keyPath, keyPEM, 0o400)
	write(t, filepath.Join(etcDir, "sensor.token"), []byte("a-bearer-token\n"), 0o400)
	write(t, filepath.Join(logDir, "sensor.log"), []byte("sensor: started\n"), 0o640)

	me, err := user.Current()
	if err != nil {
		t.Fatal(err)
	}
	f.env = doctorEnv{
		etcDir:    etcDir,
		logDir:    logDir,
		user:      me.Username,
		bpfDevs:   []string{filepath.Join(root, "no-bpf-here")},
		timeout:   2 * time.Second,
		buildInfo: "synapse-sensor 0.0.0-test",
		goos:      runtime.GOOS,
	}
	return f
}

// writeConf renders a sensor.conf with the given flag string and points the env
// at it.
func (f *doctorFixture) writeConf(t *testing.T, extraVars map[string]string, args string) {
	t.Helper()
	var b strings.Builder
	b.WriteString("# Generated by OPNsense - do not edit.\n")
	b.WriteString("synapseids_sensor_enable=\"YES\"\n")
	b.WriteString("synapseids_sensor_iface=\"" + f.iface + "\"\n")
	b.WriteString("synapseids_sensor_iface_id=\"wan\"\n")
	b.WriteString("synapseids_sensor_iface_src=\"interfaces.wan.if\"\n")
	b.WriteString("synapseids_sensor_iface_error=\"\"\n")
	for k, v := range extraVars {
		b.WriteString(k + "=\"" + v + "\"\n")
	}
	b.WriteString("synapseids_sensor_args=\"" + args + "\"\n")

	path := filepath.Join(f.etcDir, "sensor.conf")
	write(t, path, []byte(b.String()), 0o640)
	f.env.confPath = path
}

// goodArgs is a fully configured listen-mode sensor on a free port.
func (f *doctorFixture) goodArgs(t *testing.T) string {
	t.Helper()
	return strings.Join([]string{
		"--listen 127.0.0.1:" + freePort(t),
		"--iface " + f.iface,
		"--filter ip-any",
		"--direction in",
		"--authorized",
		"--cert " + f.certPath,
		"--key " + f.keyPath,
		"--client-ca " + f.caPath,
		"--token-file " + filepath.Join(f.etcDir, "sensor.token"),
	}, " ")
}

func write(t *testing.T, path string, data []byte, mode os.FileMode) {
	t.Helper()
	if err := os.WriteFile(path, data, mode); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(path, mode); err != nil {
		t.Fatal(err)
	}
}

func firstLocalInterface(t *testing.T) string {
	t.Helper()
	ifaces, err := net.Interfaces()
	if err != nil || len(ifaces) == 0 {
		t.Skip("no network interfaces to test against")
	}
	for _, i := range ifaces {
		if i.Flags&net.FlagUp != 0 {
			return i.Name
		}
	}
	return ifaces[0].Name
}

func freePort(t *testing.T) string {
	t.Helper()
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = ln.Close() }()
	_, port, err := net.SplitHostPort(ln.Addr().String())
	if err != nil {
		t.Fatal(err)
	}
	return port
}

// statusOf returns the status of the named check, and whether it was present.
func statusOf(results []checkResult, name string) (checkStatus, string, bool) {
	for _, r := range results {
		if r.name == name {
			return r.status, r.detail, true
		}
	}
	return 0, "", false
}

func wantStatus(t *testing.T, results []checkResult, name string, want checkStatus) {
	t.Helper()
	got, detail, ok := statusOf(results, name)
	if !ok {
		t.Fatalf("check %q not present in %v", name, names(results))
	}
	if got != want {
		t.Errorf("check %q = %s (%s), want %s", name, got.label(), detail, want.label())
	}
}

func names(results []checkResult) []string {
	out := make([]string, 0, len(results))
	for _, r := range results {
		out = append(out, r.name)
	}
	return out
}

// ---------------------------------------------------------------- checks

// A correctly deployed sensor must produce no [FAIL] line at all. This is the
// test that pins the whole happy path, including the one thing the plugin was
// missing before #104: rendered, parseable, correctly-permissioned PEM material.
func TestDoctorHealthyDeployment(t *testing.T) {
	f := newDoctorFixture(t)
	f.writeConf(t, nil, f.goodArgs(t))

	results := runChecks(f.env)
	for _, r := range results {
		if r.status == statusFail {
			t.Errorf("unexpected FAIL %s: %s", r.name, r.detail)
		}
	}
	for _, name := range []string{"binary", "config", "interface", "token-file", "tls-identity", "tls-trust", "log-sink", "collector"} {
		if _, _, ok := statusOf(results, name); !ok {
			t.Errorf("missing check %q; got %v", name, names(results))
		}
	}
	wantStatus(t, results, "config", statusPass)
	wantStatus(t, results, "interface", statusPass)
	wantStatus(t, results, "token-file", statusPass)
	wantStatus(t, results, "tls-identity", statusPass)
	wantStatus(t, results, "tls-trust", statusPass)
	wantStatus(t, results, "log-sink", statusPass)

	var sb strings.Builder
	if code := reportDoctor(&sb, results); code != 0 {
		t.Errorf("reportDoctor exit = %d, want 0\n%s", code, sb.String())
	}
	if !strings.Contains(sb.String(), "selftest: PASSED") {
		t.Errorf("output lacks the PASSED summary:\n%s", sb.String())
	}
	t.Logf("healthy deployment selftest output:\n%s", sb.String())
}

// The interface check is the one issue #102 calls out as "silently produces a
// sensor bound to nothing", so it gets its own table.
func TestDoctorInterfaceResolution(t *testing.T) {
	t.Run("device does not exist", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.iface = "definitely-not-a-device0"
		f.writeConf(t, nil, "--listen 127.0.0.1:"+freePort(t)+" --iface definitely-not-a-device0 --authorized")
		results := runChecks(f.env)
		wantStatus(t, results, "interface", statusFail)
		_, detail, _ := statusOf(results, "interface")
		if !strings.Contains(detail, "does not exist") {
			t.Errorf("detail = %q, want it to name the missing device", detail)
		}
		// The remedy must enumerate what *is* present — that is the diagnostic.
		var remedy string
		for _, r := range results {
			if r.name == "interface" {
				remedy = strings.Join(r.remedy, "\n")
			}
		}
		if !strings.Contains(remedy, "Devices present:") {
			t.Errorf("remedy does not list the available devices:\n%s", remedy)
		}
	})

	t.Run("template could not resolve the identifier", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t,
			map[string]string{"synapseids_sensor_iface_error": "identifier wan is not in the interfaces node and helpers.physical_interface is unavailable"},
			"--listen 127.0.0.1:"+freePort(t)+" --authorized")
		results := runChecks(f.env)
		wantStatus(t, results, "interface", statusFail)
		_, detail, _ := statusOf(results, "interface")
		if !strings.Contains(detail, "helpers.physical_interface") {
			t.Errorf("detail = %q, want the template's recorded lookup attempt", detail)
		}
	})

	t.Run("no interface at all", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, map[string]string{"synapseids_sensor_iface": ""},
			"--listen 127.0.0.1:"+freePort(t)+" --authorized")
		// writeConf writes iface before extraVars, so the later empty value wins.
		results := runChecks(f.env)
		wantStatus(t, results, "interface", statusFail)
	})
}

func TestDoctorTokenFile(t *testing.T) {
	t.Run("world readable", func(t *testing.T) {
		f := newDoctorFixture(t)
		write(t, filepath.Join(f.etcDir, "sensor.token"), []byte("tok\n"), 0o444)
		f.writeConf(t, nil, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "token-file", statusFail)
		_, detail, _ := statusOf(results, "token-file")
		if !strings.Contains(detail, "readable by more than the owner") {
			t.Errorf("detail = %q", detail)
		}
	})

	t.Run("empty", func(t *testing.T) {
		f := newDoctorFixture(t)
		write(t, filepath.Join(f.etcDir, "sensor.token"), nil, 0o400)
		f.writeConf(t, nil, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "token-file", statusFail)
	})

	t.Run("missing", func(t *testing.T) {
		f := newDoctorFixture(t)
		if err := os.Remove(filepath.Join(f.etcDir, "sensor.token")); err != nil {
			t.Fatal(err)
		}
		f.writeConf(t, nil, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "token-file", statusFail)
	})
}

// #104: the private key must never be readable by anyone but the service user,
// and a missing PEM must stay a hard failure rather than a downgrade.
func TestDoctorTLSMaterial(t *testing.T) {
	t.Run("key world readable", func(t *testing.T) {
		f := newDoctorFixture(t)
		if err := os.Chmod(f.keyPath, 0o444); err != nil {
			t.Fatal(err)
		}
		f.writeConf(t, nil, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "tls-identity", statusFail)
		_, detail, _ := statusOf(results, "tls-identity")
		if !strings.Contains(detail, "readable by more than its owner") {
			t.Errorf("detail = %q", detail)
		}
	})

	t.Run("key missing is a hard failure", func(t *testing.T) {
		f := newDoctorFixture(t)
		if err := os.Remove(f.keyPath); err != nil {
			t.Fatal(err)
		}
		f.writeConf(t, nil, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "tls-identity", statusFail)
	})

	t.Run("mismatched pair", func(t *testing.T) {
		f := newDoctorFixture(t)
		_, _, otherKey, err := pcapoverip.SelfSignedCert("127.0.0.1")
		if err != nil {
			t.Fatal(err)
		}
		write(t, f.keyPath, otherKey, 0o400)
		f.writeConf(t, nil, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "tls-identity", statusFail)
	})

	t.Run("half a pair", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--listen 127.0.0.1:"+freePort(t)+" --iface "+f.iface+
			" --authorized --cert "+f.certPath)
		results := runChecks(f.env)
		wantStatus(t, results, "tls-identity", statusFail)
	})

	t.Run("a private key pasted into the CA field", func(t *testing.T) {
		f := newDoctorFixture(t)
		_, _, keyPEM, err := pcapoverip.SelfSignedCert("127.0.0.1")
		if err != nil {
			t.Fatal(err)
		}
		write(t, f.caPath, keyPEM, 0o444)
		f.writeConf(t, nil, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "tls-trust", statusFail)
		_, detail, _ := statusOf(results, "tls-trust")
		if !strings.Contains(detail, "not a certificate") {
			t.Errorf("detail = %q", detail)
		}
	})

	t.Run("no TLS material configured", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--listen 127.0.0.1:"+freePort(t)+" --iface "+f.iface+" --authorized")
		results := runChecks(f.env)
		wantStatus(t, results, "tls-identity", statusSkip)
		wantStatus(t, results, "tls-trust", statusSkip)
	})

	t.Run("insecure-tls warns loudly", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--connect 127.0.0.1:"+freePort(t)+" --iface "+f.iface+
			" --authorized --insecure-tls")
		f.env.skipDial = true
		results := runChecks(f.env)
		wantStatus(t, results, "tls-trust", statusWarn)
		_, detail, _ := statusOf(results, "tls-trust")
		if !strings.Contains(detail, "NOT verified") {
			t.Errorf("detail = %q", detail)
		}
	})
}

func TestDoctorConfigChecks(t *testing.T) {
	t.Run("missing config file", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.env.confPath = filepath.Join(f.etcDir, "not-rendered.conf")
		results := runChecks(f.env)
		wantStatus(t, results, "config", statusFail)
	})

	t.Run("missing --authorized", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--listen 127.0.0.1:"+freePort(t)+" --iface "+f.iface)
		results := runChecks(f.env)
		wantStatus(t, results, "config", statusFail)
		_, detail, _ := statusOf(results, "config")
		_ = detail
	})

	t.Run("unknown filter preset", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--listen 127.0.0.1:"+freePort(t)+" --iface "+f.iface+
			" --authorized --filter bogus-preset")
		results := runChecks(f.env)
		wantStatus(t, results, "config", statusFail)
	})

	t.Run("disabled sensor warns", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, map[string]string{"synapseids_sensor_enable": "NO"}, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "config", statusWarn)
	})
}

func TestDoctorCollector(t *testing.T) {
	t.Run("connect reachable", func(t *testing.T) {
		ln, err := net.Listen("tcp", "127.0.0.1:0")
		if err != nil {
			t.Fatal(err)
		}
		defer func() { _ = ln.Close() }()
		go func() {
			for {
				c, err := ln.Accept()
				if err != nil {
					return
				}
				_ = c.Close()
			}
		}()
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--connect "+ln.Addr().String()+" --iface "+f.iface+" --authorized")
		results := runChecks(f.env)
		wantStatus(t, results, "collector", statusPass)
	})

	t.Run("connect refused", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--connect 127.0.0.1:"+freePort(t)+" --iface "+f.iface+" --authorized")
		results := runChecks(f.env)
		wantStatus(t, results, "collector", statusFail)
	})

	t.Run("skip-dial", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.env.skipDial = true
		f.writeConf(t, nil, "--connect 10.255.255.1:4789 --iface "+f.iface+" --authorized")
		results := runChecks(f.env)
		wantStatus(t, results, "collector", statusSkip)
	})

	t.Run("listen port already bound", func(t *testing.T) {
		ln, err := net.Listen("tcp", "127.0.0.1:0")
		if err != nil {
			t.Fatal(err)
		}
		defer func() { _ = ln.Close() }()
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--listen "+ln.Addr().String()+" --iface "+f.iface+" --authorized")
		results := runChecks(f.env)
		wantStatus(t, results, "collector", statusPass)
	})

	t.Run("listen port free means not running", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--listen 127.0.0.1:"+freePort(t)+" --iface "+f.iface+" --authorized")
		results := runChecks(f.env)
		wantStatus(t, results, "collector", statusWarn)
	})

	t.Run("unbindable listen address", func(t *testing.T) {
		f := newDoctorFixture(t)
		f.writeConf(t, nil, "--listen 10.255.255.1:4789 --iface "+f.iface+" --authorized")
		results := runChecks(f.env)
		wantStatus(t, results, "collector", statusFail)
	})
}

func TestDoctorLogSink(t *testing.T) {
	t.Run("log missing warns with the daemon -f remedy", func(t *testing.T) {
		f := newDoctorFixture(t)
		if err := os.Remove(filepath.Join(f.logDir, "sensor.log")); err != nil {
			t.Fatal(err)
		}
		f.writeConf(t, nil, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "log-sink", statusWarn)
		var remedy string
		for _, r := range results {
			if r.name == "log-sink" {
				remedy = strings.Join(r.remedy, "\n")
			}
		}
		if !strings.Contains(remedy, "-f") {
			t.Errorf("remedy should name the daemon(8) -f remedy:\n%s", remedy)
		}
	})

	t.Run("log directory missing fails", func(t *testing.T) {
		f := newDoctorFixture(t)
		if err := os.RemoveAll(f.logDir); err != nil {
			t.Fatal(err)
		}
		f.writeConf(t, nil, f.goodArgs(t))
		results := runChecks(f.env)
		wantStatus(t, results, "log-sink", statusFail)
	})
}

func TestDoctorBPFAccessSkippedOffFreeBSD(t *testing.T) {
	f := newDoctorFixture(t)
	f.writeConf(t, nil, f.goodArgs(t))
	f.env.goos = "linux"
	results := runChecks(f.env)
	wantStatus(t, results, "bpf-access", statusSkip)

	// On a FreeBSD build with no device node present at all, it must fail rather
	// than pass silently: the sensor would capture nothing.
	f.env.goos = "freebsd"
	results = runChecks(f.env)
	wantStatus(t, results, "bpf-access", statusFail)
}

func TestDoctorServiceUserMissing(t *testing.T) {
	f := newDoctorFixture(t)
	f.env.user = "definitely-no-such-user-synapseids"
	f.writeConf(t, nil, f.goodArgs(t))
	results := runChecks(f.env)
	wantStatus(t, results, "service-user", statusFail)
}

// reportDoctor's exit status is the contract the rc.d verb and the configd
// action rely on.
func TestReportDoctorExitStatus(t *testing.T) {
	var sb strings.Builder
	if code := reportDoctor(&sb, []checkResult{pass("a", "ok"), warn("b", "hmm", "do this"), skip("c", "n/a")}); code != 0 {
		t.Errorf("exit = %d, want 0 (a warning must not fail the run)", code)
	}
	if !strings.Contains(sb.String(), "       do this") {
		t.Errorf("remedy lines must be indented under their check:\n%s", sb.String())
	}
	sb.Reset()
	if code := reportDoctor(&sb, []checkResult{pass("a", "ok"), fail("b", "broken")}); code != 1 {
		t.Errorf("exit = %d, want 1", code)
	}
	if !strings.Contains(sb.String(), "selftest: FAILED") {
		t.Errorf("output lacks the FAILED summary:\n%s", sb.String())
	}
}

// The status labels are what an operator greps for, so pin them.
func TestCheckStatusLabels(t *testing.T) {
	for status, want := range map[checkStatus]string{
		statusPass: "[ OK ]",
		statusWarn: "[WARN]",
		statusFail: "[FAIL]",
		statusSkip: "[SKIP]",
	} {
		if got := status.label(); got != want {
			t.Errorf("label = %q, want %q", got, want)
		}
	}
}

func TestRunDoctorHelpExitsZero(t *testing.T) {
	if code := runDoctor([]string{"--help"}); code != 0 {
		t.Errorf("runDoctor --help = %d, want 0", code)
	}
	if code := runDoctor([]string{"--not-a-flag"}); code != 2 {
		t.Errorf("runDoctor --not-a-flag = %d, want 2", code)
	}
}
